// Mocks generated by Mockito 5.4.2 from annotations
// in wordy/test/remote_source_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:wordy/data/network/api_service.dart' as _i25;
import 'package:wordy/data/network/remote_source.dart' as _i4;
import 'package:wordy/data/network/request/login_user_request.dart' as _i8;
import 'package:wordy/data/network/request/register_user_request.dart' as _i10;
import 'package:wordy/data/network/response/course_list_response.dart' as _i20;
import 'package:wordy/data/network/response/flash_card_list_response.dart'
    as _i16;
import 'package:wordy/data/network/response/known_word_list.dart' as _i6;
import 'package:wordy/data/network/response/language_list_response.dart'
    as _i12;
import 'package:wordy/data/network/response/login_user_response.dart' as _i7;
import 'package:wordy/data/network/response/refresh_token_response.dart'
    as _i23;
import 'package:wordy/data/network/response/register_user_response.dart' as _i9;
import 'package:wordy/data/network/response/registeration_response.dart'
    as _i11;
import 'package:wordy/data/network/response/topic_list_response.dart' as _i24;
import 'package:wordy/data/network/response/update_registeration_status_response.dart'
    as _i14;
import 'package:wordy/data/network/response/update_user_current_course_response.dart'
    as _i15;
import 'package:wordy/data/network/response/update_user_interface_language_response.dart'
    as _i13;
import 'package:wordy/domain/models/active_course.dart' as _i21;
import 'package:wordy/domain/models/profile_data.dart' as _i22;
import 'package:wordy/domain/models/user_active_courses_progress.dart' as _i19;
import 'package:wordy/domain/models/user_course.dart' as _i18;
import 'package:wordy/domain/models/user_settings.dart' as _i17;
import 'package:wordy/utility/either.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<Exception, R> extends _i1.SmartFake
    implements _i2.Either<Exception, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDio_1 extends _i1.SmartFake implements _i3.Dio {
  _FakeDio_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCancelToken_2 extends _i1.SmartFake implements _i3.CancelToken {
  _FakeCancelToken_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeResponse_3<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBaseOptions_4 extends _i1.SmartFake implements _i3.BaseOptions {
  _FakeBaseOptions_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientAdapter_5 extends _i1.SmartFake
    implements _i3.HttpClientAdapter {
  _FakeHttpClientAdapter_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTransformer_6 extends _i1.SmartFake implements _i3.Transformer {
  _FakeTransformer_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeInterceptors_7 extends _i1.SmartFake implements _i3.Interceptors {
  _FakeInterceptors_7(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [RemoteSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteSource extends _i1.Mock implements _i4.RemoteSource {
  @override
  _i5.Future<
      _i2.Either<_i3.DioException, _i6.KnownWordList>> getLearnedWordsByTopic(
    String? topic,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLearnedWordsByTopic,
          [
            topic,
            token,
          ],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>.value(
                _FakeEither_0<_i3.DioException, _i6.KnownWordList>(
          this,
          Invocation.method(
            #getLearnedWordsByTopic,
            [
              topic,
              token,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>.value(
                _FakeEither_0<_i3.DioException, _i6.KnownWordList>(
          this,
          Invocation.method(
            #getLearnedWordsByTopic,
            [
              topic,
              token,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>> getWordsByTopic(
          String? topic) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWordsByTopic,
          [topic],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>.value(
                _FakeEither_0<_i3.DioException, _i6.KnownWordList>(
          this,
          Invocation.method(
            #getWordsByTopic,
            [topic],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>.value(
                _FakeEither_0<_i3.DioException, _i6.KnownWordList>(
          this,
          Invocation.method(
            #getWordsByTopic,
            [topic],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, _i7.LoginUserResponse>> loginUser(
          _i8.LoginUserRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #loginUser,
          [request],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i3.DioException, _i7.LoginUserResponse>>.value(
            _FakeEither_0<_i3.DioException, _i7.LoginUserResponse>(
          this,
          Invocation.method(
            #loginUser,
            [request],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException, _i7.LoginUserResponse>>.value(
            _FakeEither_0<_i3.DioException, _i7.LoginUserResponse>(
          this,
          Invocation.method(
            #loginUser,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i7.LoginUserResponse>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException, _i9.RegisterUserResponse>> registerUser(
          _i10.RegisterUserRequest? request) =>
      (super.noSuchMethod(
        Invocation.method(
          #registerUser,
          [request],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i3.DioException, _i9.RegisterUserResponse>>.value(
            _FakeEither_0<_i3.DioException, _i9.RegisterUserResponse>(
          this,
          Invocation.method(
            #registerUser,
            [request],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException, _i9.RegisterUserResponse>>.value(
            _FakeEither_0<_i3.DioException, _i9.RegisterUserResponse>(
          this,
          Invocation.method(
            #registerUser,
            [request],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i9.RegisterUserResponse>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException,
          _i11.RegisterationResponse>> getRegisterationStatus(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRegisterationStatus,
          [token],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i3.DioException, _i11.RegisterationResponse>>.value(
            _FakeEither_0<_i3.DioException, _i11.RegisterationResponse>(
          this,
          Invocation.method(
            #getRegisterationStatus,
            [token],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException, _i11.RegisterationResponse>>.value(
            _FakeEither_0<_i3.DioException, _i11.RegisterationResponse>(
          this,
          Invocation.method(
            #getRegisterationStatus,
            [token],
          ),
        )),
      ) as _i5
          .Future<_i2.Either<_i3.DioException, _i11.RegisterationResponse>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException,
          _i12.LanguageListResponse>> getAvailableLanguages() =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableLanguages,
          [],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i3.DioException, _i12.LanguageListResponse>>.value(
            _FakeEither_0<_i3.DioException, _i12.LanguageListResponse>(
          this,
          Invocation.method(
            #getAvailableLanguages,
            [],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException, _i12.LanguageListResponse>>.value(
            _FakeEither_0<_i3.DioException, _i12.LanguageListResponse>(
          this,
          Invocation.method(
            #getAvailableLanguages,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i12.LanguageListResponse>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException,
          _i13.UpdateUserInterfaceLanguageResponse>> switchInterfaceLanguage(
    String? token,
    String? languageName,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #switchInterfaceLanguage,
          [
            token,
            languageName,
          ],
        ),
        returnValue: _i5.Future<
            _i2.Either<_i3.DioException,
                _i13.UpdateUserInterfaceLanguageResponse>>.value(_FakeEither_0<
            _i3.DioException, _i13.UpdateUserInterfaceLanguageResponse>(
          this,
          Invocation.method(
            #switchInterfaceLanguage,
            [
              token,
              languageName,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
            _i2.Either<_i3.DioException,
                _i13.UpdateUserInterfaceLanguageResponse>>.value(_FakeEither_0<
            _i3.DioException, _i13.UpdateUserInterfaceLanguageResponse>(
          this,
          Invocation.method(
            #switchInterfaceLanguage,
            [
              token,
              languageName,
            ],
          ),
        )),
      ) as _i5.Future<
          _i2.Either<_i3.DioException,
              _i13.UpdateUserInterfaceLanguageResponse>>);
  @override
  _i5.Future<
          _i2.Either<_i3.DioException, _i14.UpdateRegisterationStatusResponse>>
      updateRegisterationStatus(String? token) => (super.noSuchMethod(
            Invocation.method(
              #updateRegisterationStatus,
              [token],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i3.DioException,
                        _i14.UpdateRegisterationStatusResponse>>.value(
                _FakeEither_0<_i3.DioException,
                    _i14.UpdateRegisterationStatusResponse>(
              this,
              Invocation.method(
                #updateRegisterationStatus,
                [token],
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                    _i2.Either<_i3.DioException,
                        _i14.UpdateRegisterationStatusResponse>>.value(
                _FakeEither_0<_i3.DioException,
                    _i14.UpdateRegisterationStatusResponse>(
              this,
              Invocation.method(
                #updateRegisterationStatus,
                [token],
              ),
            )),
          ) as _i5.Future<
              _i2.Either<_i3.DioException,
                  _i14.UpdateRegisterationStatusResponse>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, _i15.UpdateUserCurrentCourseResponse>>
      switchCurrentCourse(
    String? courseName,
    String? token,
  ) =>
          (super.noSuchMethod(
            Invocation.method(
              #switchCurrentCourse,
              [
                courseName,
                token,
              ],
            ),
            returnValue: _i5.Future<
                _i2.Either<_i3.DioException,
                    _i15.UpdateUserCurrentCourseResponse>>.value(_FakeEither_0<
                _i3.DioException, _i15.UpdateUserCurrentCourseResponse>(
              this,
              Invocation.method(
                #switchCurrentCourse,
                [
                  courseName,
                  token,
                ],
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException,
                    _i15.UpdateUserCurrentCourseResponse>>.value(_FakeEither_0<
                _i3.DioException, _i15.UpdateUserCurrentCourseResponse>(
              this,
              Invocation.method(
                #switchCurrentCourse,
                [
                  courseName,
                  token,
                ],
              ),
            )),
          ) as _i5.Future<
              _i2.Either<_i3.DioException,
                  _i15.UpdateUserCurrentCourseResponse>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException,
          _i16.FlashCardListResponse>> createFlashCardList(
    String? topic,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createFlashCardList,
          [
            topic,
            token,
          ],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i3.DioException, _i16.FlashCardListResponse>>.value(
            _FakeEither_0<_i3.DioException, _i16.FlashCardListResponse>(
          this,
          Invocation.method(
            #createFlashCardList,
            [
              topic,
              token,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException, _i16.FlashCardListResponse>>.value(
            _FakeEither_0<_i3.DioException, _i16.FlashCardListResponse>(
          this,
          Invocation.method(
            #createFlashCardList,
            [
              topic,
              token,
            ],
          ),
        )),
      ) as _i5
          .Future<_i2.Either<_i3.DioException, _i16.FlashCardListResponse>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException,
          _i16.FlashCardListResponse>> getBeginnerQuizWordList(
    String? topic,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBeginnerQuizWordList,
          [
            topic,
            token,
          ],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i3.DioException, _i16.FlashCardListResponse>>.value(
            _FakeEither_0<_i3.DioException, _i16.FlashCardListResponse>(
          this,
          Invocation.method(
            #getBeginnerQuizWordList,
            [
              topic,
              token,
            ],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException, _i16.FlashCardListResponse>>.value(
            _FakeEither_0<_i3.DioException, _i16.FlashCardListResponse>(
          this,
          Invocation.method(
            #getBeginnerQuizWordList,
            [
              topic,
              token,
            ],
          ),
        )),
      ) as _i5
          .Future<_i2.Either<_i3.DioException, _i16.FlashCardListResponse>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException, _i6.KnownWordList>> getLearnedWordList(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getLearnedWordList,
          [token],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>.value(
                _FakeEither_0<_i3.DioException, _i6.KnownWordList>(
          this,
          Invocation.method(
            #getLearnedWordList,
            [token],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>.value(
                _FakeEither_0<_i3.DioException, _i6.KnownWordList>(
          this,
          Invocation.method(
            #getLearnedWordList,
            [token],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i6.KnownWordList>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, void>> insertLearnedWordList(
    List<int>? wordIdList,
    String? token,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertLearnedWordList,
          [
            wordIdList,
            token,
          ],
        ),
        returnValue: _i5.Future<_i2.Either<_i3.DioException, void>>.value(
            _FakeEither_0<_i3.DioException, void>(
          this,
          Invocation.method(
            #insertLearnedWordList,
            [
              wordIdList,
              token,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, void>>.value(
                _FakeEither_0<_i3.DioException, void>(
          this,
          Invocation.method(
            #insertLearnedWordList,
            [
              wordIdList,
              token,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, void>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, _i17.UserSettings>> getUserSettings(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserSettings,
          [token],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i3.DioException, _i17.UserSettings>>.value(
                _FakeEither_0<_i3.DioException, _i17.UserSettings>(
          this,
          Invocation.method(
            #getUserSettings,
            [token],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, _i17.UserSettings>>.value(
                _FakeEither_0<_i3.DioException, _i17.UserSettings>(
          this,
          Invocation.method(
            #getUserSettings,
            [token],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i17.UserSettings>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, _i18.UserCourse>>
      getUserCurrentCourse(String? token) => (super.noSuchMethod(
            Invocation.method(
              #getUserCurrentCourse,
              [token],
            ),
            returnValue:
                _i5.Future<_i2.Either<_i3.DioException, _i18.UserCourse>>.value(
                    _FakeEither_0<_i3.DioException, _i18.UserCourse>(
              this,
              Invocation.method(
                #getUserCurrentCourse,
                [token],
              ),
            )),
            returnValueForMissingStub:
                _i5.Future<_i2.Either<_i3.DioException, _i18.UserCourse>>.value(
                    _FakeEither_0<_i3.DioException, _i18.UserCourse>(
              this,
              Invocation.method(
                #getUserCurrentCourse,
                [token],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i3.DioException, _i18.UserCourse>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, bool>> cancelRequest() =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelRequest,
          [],
        ),
        returnValue: _i5.Future<_i2.Either<_i3.DioException, bool>>.value(
            _FakeEither_0<_i3.DioException, bool>(
          this,
          Invocation.method(
            #cancelRequest,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, bool>>.value(
                _FakeEither_0<_i3.DioException, bool>(
          this,
          Invocation.method(
            #cancelRequest,
            [],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, bool>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, _i19.UserActiveCoursesProgress>>
      getUserActiveCoursesProgress(String? token) => (super.noSuchMethod(
            Invocation.method(
              #getUserActiveCoursesProgress,
              [token],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i3.DioException,
                        _i19.UserActiveCoursesProgress>>.value(
                _FakeEither_0<_i3.DioException, _i19.UserActiveCoursesProgress>(
              this,
              Invocation.method(
                #getUserActiveCoursesProgress,
                [token],
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                    _i2.Either<_i3.DioException,
                        _i19.UserActiveCoursesProgress>>.value(
                _FakeEither_0<_i3.DioException, _i19.UserActiveCoursesProgress>(
              this,
              Invocation.method(
                #getUserActiveCoursesProgress,
                [token],
              ),
            )),
          ) as _i5.Future<
              _i2.Either<_i3.DioException, _i19.UserActiveCoursesProgress>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException,
          _i20.CourseListResponse>> getAvailableCourses(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAvailableCourses,
          [token],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i3.DioException, _i20.CourseListResponse>>.value(
            _FakeEither_0<_i3.DioException, _i20.CourseListResponse>(
          this,
          Invocation.method(
            #getAvailableCourses,
            [token],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException, _i20.CourseListResponse>>.value(
            _FakeEither_0<_i3.DioException, _i20.CourseListResponse>(
          this,
          Invocation.method(
            #getAvailableCourses,
            [token],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i20.CourseListResponse>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException,
          _i21.ActiveCourse>> getUserCurrentCourseProgress(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserCurrentCourseProgress,
          [token],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i3.DioException, _i21.ActiveCourse>>.value(
                _FakeEither_0<_i3.DioException, _i21.ActiveCourse>(
          this,
          Invocation.method(
            #getUserCurrentCourseProgress,
            [token],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, _i21.ActiveCourse>>.value(
                _FakeEither_0<_i3.DioException, _i21.ActiveCourse>(
          this,
          Invocation.method(
            #getUserCurrentCourseProgress,
            [token],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i21.ActiveCourse>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, _i22.ProfileData>> getProfileData(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #getProfileData,
          [token],
        ),
        returnValue:
            _i5.Future<_i2.Either<_i3.DioException, _i22.ProfileData>>.value(
                _FakeEither_0<_i3.DioException, _i22.ProfileData>(
          this,
          Invocation.method(
            #getProfileData,
            [token],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, _i22.ProfileData>>.value(
                _FakeEither_0<_i3.DioException, _i22.ProfileData>(
          this,
          Invocation.method(
            #getProfileData,
            [token],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i22.ProfileData>>);
  @override
  _i5.Future<
      _i2.Either<_i3.DioException, _i23.RefreshTokenResponse>> refreshToken(
          String? refreshToken) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshToken,
          [refreshToken],
        ),
        returnValue: _i5.Future<
                _i2.Either<_i3.DioException, _i23.RefreshTokenResponse>>.value(
            _FakeEither_0<_i3.DioException, _i23.RefreshTokenResponse>(
          this,
          Invocation.method(
            #refreshToken,
            [refreshToken],
          ),
        )),
        returnValueForMissingStub: _i5.Future<
                _i2.Either<_i3.DioException, _i23.RefreshTokenResponse>>.value(
            _FakeEither_0<_i3.DioException, _i23.RefreshTokenResponse>(
          this,
          Invocation.method(
            #refreshToken,
            [refreshToken],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, _i23.RefreshTokenResponse>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, String>> recoverAccount(
          String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #recoverAccount,
          [email],
        ),
        returnValue: _i5.Future<_i2.Either<_i3.DioException, String>>.value(
            _FakeEither_0<_i3.DioException, String>(
          this,
          Invocation.method(
            #recoverAccount,
            [email],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, String>>.value(
                _FakeEither_0<_i3.DioException, String>(
          this,
          Invocation.method(
            #recoverAccount,
            [email],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, String>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, String>> updateUserPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserPassword,
          [
            email,
            password,
          ],
        ),
        returnValue: _i5.Future<_i2.Either<_i3.DioException, String>>.value(
            _FakeEither_0<_i3.DioException, String>(
          this,
          Invocation.method(
            #updateUserPassword,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, String>>.value(
                _FakeEither_0<_i3.DioException, String>(
          this,
          Invocation.method(
            #updateUserPassword,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, String>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, String>> validateResetPassword(
    String? email,
    String? resetPasswordToken,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateResetPassword,
          [
            email,
            resetPasswordToken,
          ],
        ),
        returnValue: _i5.Future<_i2.Either<_i3.DioException, String>>.value(
            _FakeEither_0<_i3.DioException, String>(
          this,
          Invocation.method(
            #validateResetPassword,
            [
              email,
              resetPasswordToken,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i2.Either<_i3.DioException, String>>.value(
                _FakeEither_0<_i3.DioException, String>(
          this,
          Invocation.method(
            #validateResetPassword,
            [
              email,
              resetPasswordToken,
            ],
          ),
        )),
      ) as _i5.Future<_i2.Either<_i3.DioException, String>>);
  @override
  _i5.Future<_i2.Either<_i3.DioException, _i24.TopicListResponse>>
      getTopics() => (super.noSuchMethod(
            Invocation.method(
              #getTopics,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i3.DioException, _i24.TopicListResponse>>.value(
                _FakeEither_0<_i3.DioException, _i24.TopicListResponse>(
              this,
              Invocation.method(
                #getTopics,
                [],
              ),
            )),
            returnValueForMissingStub: _i5.Future<
                    _i2.Either<_i3.DioException, _i24.TopicListResponse>>.value(
                _FakeEither_0<_i3.DioException, _i24.TopicListResponse>(
              this,
              Invocation.method(
                #getTopics,
                [],
              ),
            )),
          ) as _i5
              .Future<_i2.Either<_i3.DioException, _i24.TopicListResponse>>);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i25.ApiService {
  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
  @override
  _i3.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_1(
          this,
          Invocation.getter(#dio),
        ),
        returnValueForMissingStub: _FakeDio_1(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i3.Dio);
  @override
  _i3.CancelToken get cancelToken => (super.noSuchMethod(
        Invocation.getter(#cancelToken),
        returnValue: _FakeCancelToken_2(
          this,
          Invocation.getter(#cancelToken),
        ),
        returnValueForMissingStub: _FakeCancelToken_2(
          this,
          Invocation.getter(#cancelToken),
        ),
      ) as _i3.CancelToken);
  @override
  set cancelToken(_i3.CancelToken? _cancelToken) => super.noSuchMethod(
        Invocation.setter(
          #cancelToken,
          _cancelToken,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<bool> cancelRequests() => (super.noSuchMethod(
        Invocation.method(
          #cancelRequests,
          [],
        ),
        returnValue: _i5.Future<bool>.value(false),
        returnValueForMissingStub: _i5.Future<bool>.value(false),
      ) as _i5.Future<bool>);
  @override
  void resetCancelToken() => super.noSuchMethod(
        Invocation.method(
          #resetCancelToken,
          [],
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.Response<dynamic>> get(
    String? endpoint, {
    Map<String, dynamic>? payload,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [endpoint],
          {
            #payload: payload,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #payload: payload,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #get,
            [endpoint],
            {
              #payload: payload,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
  @override
  _i5.Future<_i3.Response<dynamic>> post(
    String? endpoint, {
    Map<String, dynamic>? payload,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [endpoint],
          {
            #payload: payload,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #payload: payload,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #post,
            [endpoint],
            {
              #payload: payload,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
  @override
  _i5.Future<dynamic> put(
    String? endpoint, {
    Map<String, dynamic>? payload,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [endpoint],
          {
            #payload: payload,
            #options: options,
          },
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
  @override
  _i5.Future<dynamic> delete(String? endpoint) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [endpoint],
        ),
        returnValue: _i5.Future<dynamic>.value(),
        returnValueForMissingStub: _i5.Future<dynamic>.value(),
      ) as _i5.Future<dynamic>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i3.Dio {
  @override
  _i3.BaseOptions get options => (super.noSuchMethod(
        Invocation.getter(#options),
        returnValue: _FakeBaseOptions_4(
          this,
          Invocation.getter(#options),
        ),
        returnValueForMissingStub: _FakeBaseOptions_4(
          this,
          Invocation.getter(#options),
        ),
      ) as _i3.BaseOptions);
  @override
  set options(_i3.BaseOptions? _options) => super.noSuchMethod(
        Invocation.setter(
          #options,
          _options,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.HttpClientAdapter get httpClientAdapter => (super.noSuchMethod(
        Invocation.getter(#httpClientAdapter),
        returnValue: _FakeHttpClientAdapter_5(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
        returnValueForMissingStub: _FakeHttpClientAdapter_5(
          this,
          Invocation.getter(#httpClientAdapter),
        ),
      ) as _i3.HttpClientAdapter);
  @override
  set httpClientAdapter(_i3.HttpClientAdapter? _httpClientAdapter) =>
      super.noSuchMethod(
        Invocation.setter(
          #httpClientAdapter,
          _httpClientAdapter,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Transformer get transformer => (super.noSuchMethod(
        Invocation.getter(#transformer),
        returnValue: _FakeTransformer_6(
          this,
          Invocation.getter(#transformer),
        ),
        returnValueForMissingStub: _FakeTransformer_6(
          this,
          Invocation.getter(#transformer),
        ),
      ) as _i3.Transformer);
  @override
  set transformer(_i3.Transformer? _transformer) => super.noSuchMethod(
        Invocation.setter(
          #transformer,
          _transformer,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i3.Interceptors get interceptors => (super.noSuchMethod(
        Invocation.getter(#interceptors),
        returnValue: _FakeInterceptors_7(
          this,
          Invocation.getter(#interceptors),
        ),
        returnValueForMissingStub: _FakeInterceptors_7(
          this,
          Invocation.getter(#interceptors),
        ),
      ) as _i3.Interceptors);
  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #head,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #headUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #headUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #get,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #getUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #post,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #postUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #postUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #put,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #putUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #putUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #patch,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #patchUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #patchUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [path],
          {
            #data: data,
            #queryParameters: queryParameters,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #delete,
            [path],
            {
              #data: data,
              #queryParameters: queryParameters,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i3.Options? options,
    _i3.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteUri,
          [uri],
          {
            #data: data,
            #options: options,
            #cancelToken: cancelToken,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #deleteUri,
            [uri],
            {
              #data: data,
              #options: options,
              #cancelToken: cancelToken,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i3.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i3.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #download,
          [
            urlPath,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #download,
            [
              urlPath,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
  @override
  _i5.Future<_i3.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i3.ProgressCallback? onReceiveProgress,
    _i3.CancelToken? cancelToken,
    bool? deleteOnError = true,
    String? lengthHeader = r'content-length',
    Object? data,
    _i3.Options? options,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #downloadUri,
          [
            uri,
            savePath,
          ],
          {
            #onReceiveProgress: onReceiveProgress,
            #cancelToken: cancelToken,
            #deleteOnError: deleteOnError,
            #lengthHeader: lengthHeader,
            #data: data,
            #options: options,
          },
        ),
        returnValue:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<dynamic>>.value(_FakeResponse_3<dynamic>(
          this,
          Invocation.method(
            #downloadUri,
            [
              uri,
              savePath,
            ],
            {
              #onReceiveProgress: onReceiveProgress,
              #cancelToken: cancelToken,
              #deleteOnError: deleteOnError,
              #lengthHeader: lengthHeader,
              #data: data,
              #options: options,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<dynamic>>);
  @override
  _i5.Future<_i3.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i3.CancelToken? cancelToken,
    _i3.Options? options,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #request,
          [url],
          {
            #data: data,
            #queryParameters: queryParameters,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #request,
            [url],
            {
              #data: data,
              #queryParameters: queryParameters,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i3.CancelToken? cancelToken,
    _i3.Options? options,
    _i3.ProgressCallback? onSendProgress,
    _i3.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #requestUri,
          [uri],
          {
            #data: data,
            #cancelToken: cancelToken,
            #options: options,
            #onSendProgress: onSendProgress,
            #onReceiveProgress: onReceiveProgress,
          },
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #requestUri,
            [uri],
            {
              #data: data,
              #cancelToken: cancelToken,
              #options: options,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            },
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
  @override
  _i5.Future<_i3.Response<T>> fetch<T>(_i3.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetch,
          [requestOptions],
        ),
        returnValue: _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
        returnValueForMissingStub:
            _i5.Future<_i3.Response<T>>.value(_FakeResponse_3<T>(
          this,
          Invocation.method(
            #fetch,
            [requestOptions],
          ),
        )),
      ) as _i5.Future<_i3.Response<T>>);
}
