class ErrorCodes {
  static String ERROR_INVALID_REFRESH_TOKEN = "ERROR_INVALID_REFRESH_TOKEN";
  static String ERROR_TOPIC_DOES_NOT_EXIST = "ERROR_TOPIC_DOES_NOT_EXIST";
  static String ERROR_USER_WITH_EMAIL_EXISTS = "ERROR_USER_WITH_EMAIL_EXISTS";
  static String ERROR_EMPTY_TOPIC = "ERROR_EMPTY_TOPIC";
  static String ERROR_USER_HAS_NO_STATISTICS = "ERROR_USER_HAS_NO_STATISTICS";
  static String ERROR_USER_DOES_NOT_EXIST = "ERROR_USER_DOES_NOT_EXIST";
  static String ERROR_INVALID_PASSWORD =
      "ERROR_INVALID_PASSWORD";

  static String ERROR_INVALID_LANGUAGE = "ERROR_INVALID_LANGUAGE";

  static String ERROR_INVALID_JWT_TOKEN = "ERROR_INVALID_JWT_TOKEN";
}
